name: Dev to Main Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Configurar o JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the Maven project
    - name: Build with Maven
      run: mvn clean package

    # Verify the target directory
    - name: Verify target directory
      run: ls -la target

    # Autenticar no Docker Hub
    - name: Authenticate Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    # Build e push da imagem Docker
    - name: Build Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          paulacng/fiap-substitutiva:${{ github.run_number }}
          paulacng/fiap-substitutiva:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
    - uses: actions/checkout@v4

    # Definir contexto Kubernetes
    - name: Definicao context kubernetes
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}

    # Deploy para o cluster Kubernetes
    - name: Deploy to kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        images: paulacng/fiap-substitutiva:${{ github.run_number }}
        manifests: |
          k8s/deployment.yaml


  CreatePR:
    runs-on: ubuntu-latest
    needs: [CD]

    steps:
      - uses: actions/checkout@v4

      # Criar PR para a branch main
      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: pr-develop-to-main
          title: "Merge develop into main"
          body: |
            This PR merges changes from `develop` into `main` after successful tests.
          labels: |
            automated-pr
          merge-method: merge
