name: Dev to Main Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Configurar o JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Executar testes com Maven
    - name: Run Tests
      run: mvn clean test

    # Autenticar no Docker Hub
    - name: Authenticate Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    # Build e push da imagem Docker
    - name: Build Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          paulacng/fiap-substitutiva:${{ github.run_number }}
          paulacng/fiap-substitutiva:latest

    # Criar PR para a branch main
    - name: Criar PR para a branch main
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        title: "Merge develop - main"
        body: |
          This PR merges changes from `dev` into `main` after successful tests.
        labels: |
          automated-pr
        merge-method: merge
